import { Language, Rubric } from './types';

export const TRANSLATIONS = {
  en: {
    slogan_pre: "",
    slogan_strike: "Not",
    slogan_post: " everyone was born with a Mjölnir",
    step1: "Configuration",
    step2: "Execution",
    step3: "Final Adjudication",
    masterCase: "Master Case Fact Pattern",
    questions: "Exam Questions",
    addQuestion: "Add Question",
    maxWeight: "Max Weight",
    rubric: "Rubric Selector",
    quickRubric: "Quick Rubric",
    advancedRubric: "Custom Rubric",
    next: "Next Phase",
    back: "Back",
    assess: "Assess Question",
    studentAnswer: "Student Answer",
    score: "Score",
    rationale: "Substantive Rationale",
    roadmap: "Growth Roadmap",
    citations: "Statutory Citations (Lex.uz)",
    totalScore: "Total Score",
    assessing: "Adjudicating...",
    rubricUI: {
      weight: "Weight",
      addCriterion: "Add Criterion",
      name: "Name",
      description: "Description",
      maxBall: "Max Points",
      total: "Total",
      delete: "Delete"
    },
    placeholders: {
      case: "Enter the complex legal fact pattern here...",
      question: "Enter exam question...",
      answer: "Paste student response here...",
      rubricName: "e.g., Legal Argumentation",
      rubricDesc: "Describe how this should be graded..."
    }
  },
  ru: {
    slogan_pre: "",
    slogan_strike: "Не",
    slogan_post: " каждому дарован Мьёльнир",
    step1: "Конфигурация",
    step2: "Исполнение",
    step3: "Вердикт",
    masterCase: "Фабула дела",
    questions: "Экзаменационные вопросы",
    addQuestion: "Добавить вопрос",
    maxWeight: "Макс. балл",
    rubric: "Рубрика оценивания",
    quickRubric: "Быстрая рубрика",
    advancedRubric: "Своя рубрика",
    next: "Следующий этап",
    back: "Назад",
    assess: "Оценить",
    studentAnswer: "Ответ студента",
    score: "Балл",
    rationale: "Обоснование",
    roadmap: "План роста",
    citations: "Законодательные ссылки (Lex.uz)",
    totalScore: "Итоговый балл",
    assessing: "Оценивание...",
    rubricUI: {
      weight: "Вес",
      addCriterion: "Добавить критерий",
      name: "Название",
      description: "Описание",
      maxBall: "Макс. балл",
      total: "Итого",
      delete: "Удалить"
    },
    placeholders: {
      case: "Введите фабулу дела...",
      question: "Введите вопрос...",
      answer: "Вставьте ответ студента...",
      rubricName: "напр., Юридическая аргументация",
      rubricDesc: "Опишите критерии оценки..."
    }
  },
  'uz-lat': {
    slogan_pre: "Mjolnir ",
    slogan_strike: "faqat",
    slogan_post: " tanlanganlar uchun emas",
    step1: "Konfiguratsiya",
    step2: "Ijro",
    step3: "Yakuniy Hukm",
    masterCase: "Asosiy Ish Fabulasi",
    questions: "Imtihon Savollari",
    addQuestion: "Savol qo'shish",
    maxWeight: "Maks. Ball",
    rubric: "Rubrika",
    quickRubric: "Tezkor rubrika",
    advancedRubric: "Maxsus rubrika",
    next: "Keyingi Bosqich",
    back: "Orqaga",
    assess: "Baholash",
    studentAnswer: "Talaba Javobi",
    score: "Ball",
    rationale: "Asosli Tushuntirish",
    roadmap: "O'sish rejasi",
    citations: "Qonunchilikka havolalar (Lex.uz)",
    totalScore: "Jami Ball",
    assessing: "Baholanmoqda...",
    rubricUI: {
      weight: "Vazn",
      addCriterion: "Mezon qo'shish",
      name: "Nomi",
      description: "Tavsifi",
      maxBall: "Maksimal ball",
      total: "Jami",
      delete: "O'chirish"
    },
    placeholders: {
      case: "Huquqiy kazusni kiriting...",
      question: "Imtihon savolini kiriting...",
      answer: "Talaba javobini shu yerga yozing...",
      rubricName: "masalan, Huquqiy argumentatsiya",
      rubricDesc: "Baholash mezonini tavsiflang..."
    }
  },
  'uz-cyr': {
    slogan_pre: "Мёлнир ",
    slogan_strike: "фақат",
    slogan_post: " танланганлар учун эмас",
    step1: "Конфигурация",
    step2: "Ижро",
    step3: "Якуний Ҳукм",
    masterCase: "Асосий Иш Фабуласи",
    questions: "Имтиҳон Саволлари",
    addQuestion: "Савол қўшиш",
    maxWeight: "Макс. Балл",
    rubric: "Рубрика",
    quickRubric: "Тезкор рубрика",
    advancedRubric: "Махсус рубрика",
    next: "Кейинги Босқич",
    back: "Орқага",
    assess: "Баҳолаш",
    studentAnswer: "Талаба Жавоби",
    score: "Балл",
    rationale: "Асосли Тушунтириш",
    roadmap: "Ўсиш режаси",
    citations: "Қонунчиликка ҳаволалар (Lex.uz)",
    totalScore: "Жами Балл",
    assessing: "Баҳоланмоқда...",
    rubricUI: {
      weight: "Вазн",
      addCriterion: "Мезон қўшиш",
      name: "Номи",
      description: "Тавсифи",
      maxBall: "Максимал балл",
      total: "Жами",
      delete: "Ўчириш"
    },
    placeholders: {
      case: "Ҳуқуқий казусни киритинг...",
      question: "Имтиҳон саволини киритинг...",
      answer: "Талаба жавобини шу ерга ёзинг...",
      rubricName: "масалан, Ҳуқуқий аргументация",
      rubricDesc: "Баҳолаш мезонини тавсифланг..."
    }
  }
};

export const DEFAULT_RUBRIC: Rubric = {
  type: 'quick',
  items: [
    { id: '1', label: 'Tegishli huquqiy normalardan foydalanish', description: 'Application of relevant legal norms', weight: 5, maxWeight: 10, enabled: true },
    { id: '2', label: 'Tegishli sudlov ishlaridan foydalanish', description: 'Use of relevant case law', weight: 4, maxWeight: 10, enabled: true },
    { id: '3', label: 'Huquqiy doktrinalardan foydalanish', description: 'Use of legal doctrines', weight: 4, maxWeight: 10, enabled: true },
    { id: '4', label: 'Huquqiy argumentatsiya', description: 'Legal argumentation quality', weight: 4, maxWeight: 10, enabled: true },
    { id: '5', label: 'Tuzilma va mantiqiylik', description: 'Structure and logic', weight: 3, maxWeight: 10, enabled: true },
    { id: '6', label: 'Huquqiy terminologiya', description: 'Legal terminology', weight: 3, maxWeight: 10, enabled: true },
    { id: '7', label: 'Amaliy qo\'llash', description: 'Practical application', weight: 3, maxWeight: 10, enabled: true },
    { id: '8', label: 'Tanqidiy tahlil', description: 'Critical analysis', weight: 3, maxWeight: 10, enabled: true },
  ]
};
